export const insecticides = [
    {
        name:"Pistal",
        link:"/insecticides/Pistal.png",
        desc:"FIPRONIL 2.92% W/W EC",
        options:["20 ml","100 ml","250 ml","500 ml","1 ltr"],
    },
    {
        name:"Adhira",
        link:"/insecticides/Adhira.png",
        desc:"EMAMECTIN BENZOATE 1.9% EC",
        options:["20 ml","100 ml","250 ml","500 ml","1 ltr"],
    },
    {
        name:"BULLET-350",
        link:"/insecticides/BULLET-350.png",
        desc:"Neem Kernel Based EC Containing Azadirachtin 0.3% w/w min (3000 ppm)",
        options:["30 ml","100 ml","250 ml","500 ml","1 ltr"],
    },
    {
        name:"Wanted",
        link:"/insecticides/Wanted.png",
        desc:"INDOXACARB 14.5% SC",
        options:["50 ml","100 ml","250 ml","500 ml"],
    },
    {
        name:"Agrimite",
        link:"/insecticides/Agrimite.png",
        desc:"Neem Seed Kernel based EC Containing Azadirachtin - 0.15% (1500 ppm) min.",
        options:["20 ml","100 ml","250 ml","500 ml","1 ltr"],
    },
    {
        name:"Saurya",
        link:"/insecticides/Saurya.png",
        desc:"THIAMETHOXAM 75% SG",
        options:["50 gm","100 gm","250 gm"],
    },

    {
        name:"Corsa",
        link:"/insecticides/CORSA.png",
        desc:"Chlorantraniliprole 18.5% SC",
        options:["10 ml","30 ml","60 ml","150 ml", "300 ml"],
    },
    {
        name:"DETHRIN 11",
        link:"/insecticides/Dethrin-11.png",
        desc:"DELTAMETHRIN 11% EC",
        options:[ "250 ml","500 ml","1 ltr"],
    },
    {
        name:"Ten Star",
        link:"/insecticides/TENSTAR.png",
        desc:"Bifenthrin 10% EC",
        options:[ "250 ml","500 ml","1 ltr"],
    },
    {
        name:"RING TARA PRO",
        link:"/insecticides/RIngTaraPro.png",
        desc:"THIAMETHOXAM 30% FS",
        options:[ "250 ml","500 ml","1 ltr"],
    },
    {
        name:"RING TARA",
        link:"/insecticides/RINGTARA.png",
        desc:"THIAMETHOXAM 25% WG",
        options:[ "100 gm","250 gm","500 gm" ],
    },
    {
        name:"Circle",
        link:"/insecticides/CIRCLE.png",
        desc:"CYPERMETHRIN 25% EC",
        options:[ "250 ml","500 ml","1 ltr"],
    },
    {
        name:"PROCURE",
        link:"/insecticides/procure.png",
        desc:"EMAMECTIN BENZOATE 5% SG",
        options:["100 gm", "250 gm","500 gm"],
    },
    {
        name:"AC-PEIDE",
        link:"/insecticides/acpride.png",
        desc:" Acetamiprid 20% SP",
        options:["100 gm","250 gm","500 gm","1 kg"],
    },
    {
        name:"TOLRADO",
        link:"/insecticides/TOLRADO.png",
        desc:"Tolfenpyrad 15% EC",
        options:[ "250 ml","500 ml","1 ltr"],
    },
    {
        name:"BIFETIN",
        link:"/insecticides/BIFETIN.png",
        desc:"Bifenthrin 2.5% EC",
        options:["250 ml","500 ml","1 ltr"],
    },
    {
        name:"AMBOZ",
        link:"/insecticides/AMBOZ.png",
        desc:"Abamectin 1.9% EC",
        options:["20 ml","100 ml","250 ml","500 ml","1 ltr"],
    },
    {
        name:"AGGOR",
        link:"/insecticides/AGGOR.png",
        desc:"Dimothate 30% EC",
        options:[ "250 ml","500 ml","1 ltr"],
    },
    {
        name:"AC-MONO",
        link:"/insecticides/AC-MONO.png",
        desc:"Monocrotophos 36% SL",
        options: ["500 ml","1 ltr"],
    },
    {
        name:"AC-PHATE",
        link:"/insecticides/AC-PHATE.png",
        desc:"Acephate 75% SP",
        options:[ "250 gm","500 gm","1 kg"],
    },
    {
        name:"AC Phate Gold",
        link:"/insecticides/ACPhateGold.png",
        desc:"Acephate 50% + imidacloprid 1.8% SP",
        options:["250 gm","500 gm","1 kg"],
    },
    {
        name:"Prophet Super",
        link:"/insecticides/PROPHETSUPER.png",
        desc:"Profenofos 40% + Cypermethin 4% EC",
        options:["500 ml","1 ltr"],
    },
    {
        name:"PROPHET",
        link:"/insecticides/PROPHET.png",
        desc:"Profenophos 50%",
        options:[ "500 ml","1 ltr"],
    },
    {
        name:"AC-CHLORA",
        link:"/insecticides/AC-CHLORA.png",
        desc:"Chlorpyriphos 20% EC",
        options:[ "250 ml","500 ml","1 ltr"],
    },
    {
        name:"AC-Chloro Super",
        link:"/insecticides/Ac-Chloro-Super.png",
        desc:"Chlorpyrifos 50% EC",
        options:["250 ml","500 ml","1 ltr"],
    },
    {
        name:"AGRI - 505",
        link:"/insecticides/AGRI-505.png",
        desc:"Chlorpyriphos 50% + Cypermethrin 5% EC",
        options:[ "250 ml","500 ml","1 ltr"],
    },
    {
        name:"BAHADUR",
        link:"/insecticides/BAHADUR.png",
        desc:"Ethion 40% + Cypermethrin 5% EC",
        options:[ "250 ml","500 ml","1 ltr"],
    },
    {
        name:"DABBANG",
        link:"/insecticides/DABBANG.png",
        desc:"Lambdacyhalothrin 5% EC",
        options:["500 ml","1 ltr"],
    },
    {
        name:"IRON",
        link:"/insecticides/IRON.png",
        desc:"Acephate 95% SG",
        options:[ "250 ml","500 ml","1 ltr"],
    },
    {
        name:"MAZOR",
        link:"/insecticides/MAZOR.png",
        desc:"Fipronil 40% + Imidacloprid 40% WG",
        options:["40 gm","100 gm","250 gm"],
    },
    {
        name:"ATTAK",
        link:"/insecticides/ATTAK.png",
        desc:"Thiamethoxim 75% SG",
        options:["50 gm","100 gm","250 gm","500 gm"],
    },
    {
        name:"CHLORO-GR",
        link:"/insecticides/CHLORO-GR.png",
        desc:"Chlorpyrifos 10% GR",
        options:[ "1 kg"],
    },
    {
        name:"Capital",
        link:"/insecticides/CAPITAL.png",
        desc:"Imidacloprid 48% FS",
        options:["50 ml","100 ml","250 ml"],
    },
    {
        name:"AgriMida",
        link:"/insecticides/Agrimida.png",
        desc:"Imidacloprid 17.8 SL",
        options:[ "100 ml","250 ml","500 ml"],
    },
    {
        name:"ANIMAL",
        link:"/insecticides/ANIMAL.png",
        desc:"Azadirachtin 0.03% (300Ppm) min.",
        options:["250 ml","500 ml","1 ltr"],
    },
    {
        name:"THIAOM",
        link:"/insecticides/THIAOM.png",
        desc:"Thiamethoxam 12.6% + Lambda-Cyhalothrin 9.5% ZC",
        options:["250 ml","500 ml","1 ltr"],
    },
    {
        name:"THUNDER",
        link:"/insecticides/THUNDER.png",
        desc:"Lamda-Cyhulothrin 4.9%",
        options:["500 ml","1 ltr"],
    },
    {
        name:"SAMRAT",
        link:"/insecticides/SAMRAT.png",
        desc:"Fipronil 5% SC",
        options:[ "250 ml","500 ml","1 ltr"],
    },
    {
        name:"Vaalida",
        link:"/insecticides/VAALIDA.png",
        desc:"Validamycin 3% L.",
        options:["250 ml","500 ml","1 ltr"],
    },
]